version: '3.5'

services:

  notification:
    build: .
    ports:
      - 8080:8080
    container_name: notifications_app
    env_file:
      - env/dev/notifications.env
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  #    networks:
  #      - network

  database:
    image: postgres # use latest official postgres version
    container_name: database

    env_file:
      - env/dev/postgres.env
    ports:
      - 5432:5432
    #    networks:
    #      - network
    # volumes:
    #   - database:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    links:
      - database
    depends_on:
      - database
    env_file:
      - env/dev/pgadmin.env
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:80

volumes:
  #  database:
  pgadmin: